### PR TITLE
Limit concurrency

### LINKED ISSUE #18: Issue in network-utility tool
The following issue had been observed while running the network utility tool-
```
Souviks-MacBook-Pro:net-utils souvik$ go run main.go 
Looking up hostnames for IP ....
kix06s01-in-f244.1e100.net.

Looking up IPs for hostname ....
172.217.27.212
2404:6800:4009:800::2014

Looking up MX records ....
Host: gmr-smtp-in.l.google.com., Pref: 5
Host: alt1.gmr-smtp-in.l.google.com., Pref: 10
Host: alt2.gmr-smtp-in.l.google.com., Pref: 20
Host: alt3.gmr-smtp-in.l.google.com., Pref: 30
Host: alt4.gmr-smtp-in.l.google.com., Pref: 40

Looking up nameservers ....

Scanning ports ....
Port: 80, IP: 216.58.196.244
Port: 443, IP: 216.58.196.244
runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fff651412c6 m=1548 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff651412c6
stack: frame={sp:0x700032d19c58, fp:0x0} stack=[0x700032c9a2b0,0x700032d19eb0)
0000700032d19b58:  00007fff651f86a0  0000020000000200 
0000700032d19b68:  0000000000000000  0000020000000200 
0000700032d19b78:  00007fff9b896240  000000000000003c 
0000700032d19b88:  0000000001173c40  0000700032d19bb0 
0000700032d19b98:  00007fff6508a616  00007fff9b896240 
0000700032d19ba8:  0000000000000045  0000700032d19be0 
0000700032d19bb8:  00007fff65092e2d  0000000000000023 
0000700032d19bc8:  00000000000000f1  00007fff9b896240 
0000700032d19bd8:  0000700032d19cf0  0000700032d19cc0 
0000700032d19be8:  00007fff6508bbc5  00007fff9afab220 
0000700032d19bf8:  000000000000003c  00007fff650d3a92 
0000700032d19c08:  00007fff650d3a92  0000000000000000 
0000700032d19c18:  0000000001312d00  0000700032d19c60 
0000700032d19c28:  00007fff650ca91d  0000000001001380 <threadentry+0> 
0000700032d19c38:  0000000000000023runtime/cgo: pthread_create failed: Resource temporarily unavailable
  0000000001001380 <threadentry+0> 
0000700032d19c48:  0000000000000023  0000000000000014 
0000700032d19c58: <00007fff651fcbf1  0000700032d1a000 
0000700032d19c68:  0000700032d19ca8  00000000000000f1 
0000700032d19c78:  0000000000000000  00007fff9b896240 
0000700032d19c88:  0000700032d19cf0  0000700032d19cc0 
0000700032d19c98:  00007fff650ab6a6  0000003000000018 
0000700032d19ca8:  00007000ffffffdf  ffffffff32d19bf0 
0000700032d19cb8:  0000000000000023  0000700032d19d50 
0000700032d19cc8:  0000000001001375 <_cgo_sys_thread_start+213>  00007fff9b8a9000 
0000700032d19cd8:  0000000000000018  0000000000080000 
0000700032d19ce8:  ffffffff651b0c99  0000000054484441 
0000700032d19cf8:  0000000000000000  0000000000000000 
0000700032d19d08:  0000000000000000  00000000000008ff 
0000700032d19d18:  0000000010010101  0000000000000000 
0000700032d19d28:  0000000000000000  45c465c22bf600ca 
0000700032d19d38:  0000700032d19dc0  000000000116ea3c 
0000700032d19d48:  0000000000000000  0000700032d19dd8 
runtime: unknown pc 0x7fff651412c6
stack: frame={sp:0x700032d19c58, fp:0x0} stack=[0x700032c9a2b0,0x700032d19eb0)
0000700032d19b58:  00007fff651f86a0  0000020000000200 
0000700032d19b68:  0000000000000000  0000020000000200 
0000700032d19b78:  00007fff9b896240  000000000000003c 
0000700032d19b88:  0000000001173c40  0000700032d19bb0 
0000700032d19b98:  00007fff6508a616  00007fff9b896240 
0000700032d19ba8:  0000000000000045  0000700032d19be0 
0000700032d19bb8:  00007fff65092e2d  0000000000000023 
0000700032d19bc8:  00000000000000f1  00007fff9b896240 
0000700032d19bd8:  0000700032d19cf0  0000700032d19cc0 
0000700032d19be8:  00007fff6508bbc5  00007fff9afab220 
0000700032d19bf8:  000000000000003c  00007fff650d3a92 
0000700032d19c08:  00007fff650d3a92  0000000000000000 
0000700032d19c18:  0000000001312d00  0000700032d19c60 
0000700032d19c28:  00007fff650ca91d  0000000001001380 <threadentry+0> 
0000700032d19c38:  0000000000000023  0000000001001380 <threadentry+0> 
0000700032d19c48:  0000000000000023  0000000000000014 
0000700032d19c58: <00007fff651fcbf1  0000700032d1a000 
0000700032d19c68:  0000700032d19ca8  00000000000000f1 
0000700032d19c78:  0000000000000000  00007fff9b896240 
0000700032d19c88:  0000700032d19cf0  0000700032d19cc0 
0000700032d19c98:  00007fff650ab6a6  0000003000000018 
0000700032d19ca8:  00007000ffffffdf  ffffffff32d19bf0 
0000700032d19cb8:  0000000000000023  0000700032d19d50 
0000700032d19cc8:  0000000001001375 <_cgo_sys_thread_start+213>  00007fff9b8a9000 
0000700032d19cd8:  0000000000000018  0000000000080000 
0000700032d19ce8:  ffffffff651b0c99  0000000054484441 
0000700032d19cf8:  0000000000000000  0000000000000000 
0000700032d19d08:  0000000000000000  00000000000008ff 
0000700032d19d18:  0000000010010101  0000000000000000 
0000700032d19d28:  0000000000000000  45c465c22bf600ca 
0000700032d19d38:  0000700032d19dc0  000000000116ea3c 
0000700032d19d48:  0000000000000000  0000700032d19dd8 

goroutine 7493 [syscall]:
syscall.syscall(0x108b240, 0x1b43, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.13/libexec/src/runtime/sys_darwin.go:63 +0x2e fp=0xc009e90760 sp=0xc009e90738 pc=0x104946e
syscall.Close(0x1b43, 0xc0005c61e0, 0xc009e907f8)
        /usr/local/Cellar/go/1.13/libexec/src/syscall/zsyscall_darwin_amd64.go:519 +0x4c fp=0xc009e907a8 sp=0xc009e90760 pc=0x1089eac
internal/poll.(*FD).destroy(0xc002932780, 0x1, 0x6202c70)
        /usr/local/Cellar/go/1.13/libexec/src/internal/poll/fd_unix.go:78 +0x43 fp=0xc009e907e0 sp=0xc009e907a8 pc=0x1096243
internal/poll.(*FD).decref(0xc002932780, 0x1b01, 0xffff)
        /usr/local/Cellar/go/1.13/libexec/src/internal/poll/fd_mutex.go:213 +0x42 fp=0xc009e90808 sp=0xc009e907e0 pc=0x1095792
internal/poll.(*FD).Close(0xc002932780, 0xc002932780, 0x0)
        /usr/local/Cellar/go/1.13/libexec/src/internal/poll/fd_unix.go:100 +0x4f fp=0xc009e90840 sp=0xc009e90808 pc=0x109630f
net.(*netFD).Close(0xc002932780, 0x1174280, 0xc009de4480)
        /usr/local/Cellar/go/1.13/libexec/src/net/fd_unix.go:184 +0x4f fp=0xc009e90870 sp=0xc009e90840 pc=0x10c7eff
net.socket(0x1174280, 0xc009de4480, 0x114b2de, 0x3, 0x2, 0x1, 0x0, 0x0, 0x11746e0, 0x0, ...)
        /usr/local/Cellar/go/1.13/libexec/src/net/sock_posix.go:71 +0x1ed fp=0xc009e90928 sp=0xc009e90870 pc=0x10d8cfd
net.internetSocket(0x1174280, 0xc009de4480, 0x114b2de, 0x3, 0x11746e0, 0x0, 0x11746e0, 0xc009ca6c60, 0x1, 0x0, ...)
        /usr/local/Cellar/go/1.13/libexec/src/net/ipsock_posix.go:141 +0x141 fp=0xc009e909b8 sp=0xc009e90928 pc=0x10d0f91
net.(*sysDialer).doDialTCP(0xc009d64880, 0x1174280, 0xc009de4480, 0x0, 0xc009ca6c60, 0x1120b60, 0x1261900, 0x0)
        /usr/local/Cellar/go/1.13/libexec/src/net/tcpsock_posix.go:65 +0xc2 fp=0xc009e90a70 sp=0xc009e909b8 pc=0x10dbab2
net.(*sysDialer).dialTCP(0xc009d64880, 0x1174280, 0xc009de4480, 0x0, 0xc009ca6c60, 0xc0809c3262, 0xc00010ec00, 0xc009e90b38)
        /usr/local/Cellar/go/1.13/libexec/src/net/tcpsock_posix.go:signal: abort trap
Souviks-MacBook-Pro:net-utils souvik$ 
```

### PR DESCRIPTION
**Pull request by souvikhaldar**
Fixes #18

### CODE REVIEW

**Comment by gaurav-gogia** [comment]
Please send pr against dev branch :)

**Review by gaurav-gogia — CHANGES_REQUESTED** [review]
Please send PR against dev branch

**Comment by souvikhaldar** [comment]
I did not get it. Can you explain?

**Comment by gaurav-gogia** [comment]
This repo has two branches namely [master](https://github.com/gaurav-gogia/dfis-utils) and [dev](https://github.com/gaurav-gogia/dfis-utils/tree/dev). Please send your pull request against the dev one :)

**Comment by souvikhaldar** [comment]
> This repo has two branches namely [master](https://github.com/gaurav-gogia/dfis-utils) and [dev](https://github.com/gaurav-gogia/dfis-utils/tree/dev). Please send your pull request against the dev one :)

Hava look at #20

**Pull request closed without merging**
