### PR TITLE
added my ideas

### PR DESCRIPTION
**Pull request by JoelPagliuca**
Hope you don't mind but I changed your formatting slightly.

Hope you like my ideas too 😁️

### CODE REVIEW

**Comment by gaurav-gogia** [comment]
Hey! Thanks for sharing your ideas. And yea its fine, I think your formatting is better. I'll update it in issue description :)

I could use some more info on this though:
A small utility for extracting different file types from unallocated space.

It kinda feels similar to file carving to me. So a bit more explanation would be helpful like give an example or steps the program could go through to achieve this task. 

Thanks! ^.^

**Comment by JoelPagliuca** [comment]
That one was there already, not very sure exactly what that tool would do myself

**Comment by gaurav-gogia** [comment]
Sorry, it's just that I am unable to see connection between ports and files from unallocated space .-.

That's what I want to know from your idea :)

**Comment by JoelPagliuca** [comment]
That's probably because File Carving wasn't my idea haha.

Finding open ports on a compromised machine and listing processes on the machine are just things I do when I believe a machine has been compromised.

**Comment by gaurav-gogia** [comment]
I see. That makes sense, thanks for sharing :)

**Pull request merged**
